version: "2"
checks:
  complex-logic:
    enabled: true
    config:
        threshold: 10
  file-lines:
    enabled: true
    config:
        threshold: 999
  method-complexity:
    enabled: true
    config:
        threshold: 10
  method-count:
    enabled: true
    config:
        threshold: 20
  method-lines:
    enabled: true
    config:
        threshold: 100
  nested-control-flow:
    enabled: true
    config:
        threshold: 4
  return-statements:
    enabled: true
    config:
        threshold: 5
  argument-count:
    enabled: false
  similar-code:
    enabled: false
  identical-code:
    enabled: false

plugins:
  eslint:
    enabled: true
    channel: "eslint-4"
    checks:
      complexity:
        enabled: false
    config:
      config: .eslintrc
  # add typescript
  # add stylelint
plugins:
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - XXX
      - TODO

exclude_patterns:
- "build/"
- "coverage/"
- "scripts/"

- "node_modules/"
- "script/"
- "**/spec/"
- "**/test/"
- "**/tests/"
- "**/*.test.js"
