export default {
    nodes: [
        { id: 'Health', group: 1 },
        { id: 'Crisis', group: 2 },
        { id: 'Refugees', group: 3 },
        { id: 'Disasters', group: 4 },
        { id: 'Population', group: 7 },
        { id: 'Diseases', group: 1 },
        { id: 'Nutrition', group: 1 },
        { id: 'Environment', group: 1 },
        { id: 'Hunger', group: 2 },
        { id: 'Famine', group: 2 },
        { id: 'Death', group: 2 },
        { id: 'Global Warming', group: 2 },
        { id: 'Migration', group: 3 },
        { id: 'Trafficking', group: 3 },
        { id: 'Language', group: 3 },
        { id: 'Cultural', group: 3 },
        { id: 'Resettlement', group: 3 },
        { id: 'Social Service', group: 3 },
        { id: 'State', group: 3 },
        { id: 'Programs', group: 3 },
        { id: 'Terrorism', group: 4 },
        { id: 'Wildfires', group: 4 },
        { id: 'Earthquake', group: 4 },
        { id: 'Landslide', group: 4 },
        { id: 'Floods', group: 4 },
        { id: 'Hurricane', group: 4 },
        { id: 'Tornado', group: 4 },
        { id: 'Pollution', group: 5 },
        { id: 'Public Health', group: 5 },
        { id: 'Biogas', group: 5 },
        { id: 'Carbon footprint', group: 5 },
        { id: 'Drinking Water', group: 5 },
        { id: 'Gasonline', group: 5 },
    ],
    links: [
        { source: 'Health', target: 'Population', value: 4 },
        { source: 'Health', target: 'Diseases', value: 4 },
        { source: 'Health', target: 'Nutrition', value: 8 },
        { source: 'Health', target: 'Environment', value: 8 },
        { source: 'Crisis', target: 'Hunger', value: 4 },
        { source: 'Crisis', target: 'Famine', value: 4 },
        { source: 'Crisis', target: 'Death', value: 8 },
        { source: 'Crisis', target: 'Environment', value: 8 },
        { source: 'Crisis', target: 'Global Warming', value: 8 },
        { source: 'Refugees', target: 'Migration', value: 4 },
        { source: 'Refugees', target: 'Trafficking', value: 4 },
        { source: 'Refugees', target: 'Language', value: 8 },
        { source: 'Refugees', target: 'Cultural', value: 8 },
        { source: 'Refugees', target: 'Resettlement', value: 8 },
        { source: 'Refugees', target: 'Social Service', value: 8 },
        { source: 'Refugees', target: 'State', value: 8 },
        { source: 'Refugees', target: 'Programs', value: 8 },
        { source: 'Disasters', target: 'Migration', value: 4 },
        { source: 'Disasters', target: 'Terrorism', value: 4 },
        { source: 'Disasters', target: 'Wildfires', value: 8 },
        { source: 'Disasters', target: 'Earthquake', value: 8 },
        { source: 'Disasters', target: 'Landslide', value: 8 },
        { source: 'Disasters', target: 'Floods', value: 1 },
        { source: 'Disasters', target: 'Hurricane', value: 2 },
        { source: 'Disasters', target: 'Tornado', value: 4 },
        { source: 'Environment', target: 'Pollution', value: 1 },
        { source: 'Environment', target: 'Global Warming', value: 4 },
        { source: 'Environment', target: 'Public Health', value: 4 },
        { source: 'Environment', target: 'Biogas', value: 2 },
        { source: 'Environment', target: 'Carbon footprint', value: 8 },
        { source: 'Environment', target: 'Drinking Water', value: 2 },
        { source: 'Environment', target: 'Gasonline', value: 8 },
        { source: 'Health', target: 'Crisis', value: 8 },
        { source: 'Health', target: 'Refugees', value: 8 },
        { source: 'Health', target: 'Disasters', value: 8 },
        { source: 'Health', target: 'Environment', value: 8 },
        { source: 'Crisis', target: 'Refugees', value: 8 },
        { source: 'Crisis', target: 'Disasters', value: 8 },
        { source: 'Crisis', target: 'Environment', value: 8 },
        { source: 'Refugees', target: 'Disasters', value: 8 },
        { source: 'Refugees', target: 'Environment', value: 8 },
    ],
};
