const initialDevLangState = {
    strings: {
        /*
           // For testing edit
           98161: 'Apple',
           98162: 'Ball',
           98163: 'Mango',
           98164: 'Orange',
         */

        1: 'Owner',
        2: 'Created',
        3: 'Published',
        5: 'Publisher',
        6: 'Assignee',
        7: 'Confidentiality',
        8: 'Status',
        9: 'Search',
        10: 'Apply filter',
        11: 'Clear filter',
        12: 'Add leads',
        13: 'Title',
        14: 'Any',
        15: 'Entries',
        16: 'Actions',
        17: 'Anybody',
        18: 'Anytime',
        20: 'Text',
        21: 'Type',
        22: 'Prev',
        23: 'Next',
        25: 'Save',
        28: 'We cannot currently preview this publisher. Please open it in a new tab or copy thRL.',
        30: 'Invalid URL',
        31: 'Project',
        32: 'URL',
        33: 'Website',
        34: 'Add new source from:',
        35: 'Drive',
        36: 'Dropbox',
        37: 'Local disk',
        38: 'Select one',
        39: 'e.g. Nepal Monitoring',
        40: 'e.g. Lead 12:21:00 PM',
        41: 'e.g. https://deeper.togglecorp.com',
        43: 'e.g. Newspaper',
        44: 'e.g. 12/12/2012',
        45: 'Enter text description here',
        47: 'Clear similar filter',
        48: 'Source preview',
        49: 'Gathering website information for preview',
        51: 'Countries',
        52: 'Search country',
        53: 'Add new country',
        54: 'Delete country',
        55: 'Are you sure you want to remove country {country}?',
        56: 'General',
        57: 'Key figures',
        58: 'Population data',
        59: 'Seasonal calendar',
        60: 'Media sources',
        61: 'Cancel',
        62: 'Save changes',
        63: 'Human Development Index',
        64: 'Under five mortality rate (per 1.000 live births)',
        65: 'Uprooted people (refugees + IDPs + returned refugees)',
        66: 'Inform score',
        67: 'Index',
        68: 'Geo-Rank',
        69: 'Geo-Score',
        70: 'Rank',
        71: 'U5M',
        72: 'Number of refugees',
        73: 'Percentage of uprooted people',
        74: 'Number of IDPs',
        75: 'Number of returned refugees',
        76: 'Risk class',
        77: 'Inform risk index',
        78: 'Hazard and exposure',
        79: 'Vulnerability',
        80: 'Lack of coping capacity',
        83: 'Source',
        87: 'Add admin level',
        88: 'Are you sure you want to remove admin level {adminLevel}?',
        89: 'Admin level',
        90: 'Admin level name',
        91: 'Country',
        92: 'Name property',
        93: 'NAME_ENGL',
        94: 'Pcode property',
        95: 'NAME_PCODE',
        96: 'Parent name property',
        97: 'NAME_ENFG',
        98: 'Parent pcode property',
        99: 'NAME_PPCODE',
        100: 'Parent admin level',
        101: 'Country code',
        102: 'NPL',
        103: 'Name',
        104: 'Nepal',
        105: 'WB region',
        106: 'Enter WB region',
        107: 'WB income region',
        108: 'Enter WB income region',
        109: 'OCHA region',
        110: 'Enter OCHA region',
        111: 'ECHO region',
        112: 'Enter ECHO region',
        113: 'UN geographical region',
        114: 'Enter UN geographical region',
        115: 'UN Geographical sub region',
        116: 'Enter UN geographical sub region',
        117: 'There are no countries.',
        118: 'Select a country to view its detail.',
        119: 'Selected county is not found.',
        120: 'Level',
        121: 'Admin level name',
        123: 'Admin levels',
        125: 'Load GEO shape file',
        129: 'Extract lead information from URL',
        130: 'Apply this value to all elements.',
        131: 'Apply this value to all elements below.',
        132: 'Preview not available',
        133: 'Are you sure you want to discard this lead?',
        134: 'Are you sure you want to delete this assessment?',
        135: 'Search similar lead',
        136: 'Edit lead',
        137: 'Remove lead',
        138: 'Add entry from this lead',
        139: 'Add subcategory',
        140: 'This lead type is unrecognized.',
        141: 'Are you sure you want to remove this lead? The lead along with all the associated entries and assessment will be removed.',
        142: 'Tabular',
        143: 'Add assessment from this lead',
        144: 'No assessment template found for this project.',
        150: 'First name',
        151: 'e.g. John',
        152: 'Last name',
        153: 'e.g. Doe',
        154: 'Organization',
        155: 'e.g. ToggleCorp',
        158: 'Edit profile',
        160: 'Rights',
        161: 'Joined at',
        163: 'Created at',
        164: 'Last modified at',
        166: 'Members',
        167: 'View usergroup',
        168: 'Edit usergroup',
        169: 'Delete usergroup',
        170: 'View project',
        171: 'Edit project',
        172: 'Delete project',
        173: 'Projects',
        174: 'Add project',
        175: 'Groups',
        176: 'Add usergroup',
        177: 'Failed to add members.',
        178: 'e.g. ACAPS',
        179: 'Create',
        180: 'Project title',
        181: 'Enter project name',
        184: 'Email',
        185: 'Start date',
        187: 'View member',
        188: 'Revoke admin rights',
        189: 'Grant admin rights',
        190: 'Delete member',
        191: 'Delete lead',
        192: 'Add member',
        193: 'Are you sure you want to delete the project {title}?',
        194: 'Are you sure you want to delete the usergroup {title}?',
        195: 'Are you sure you want to revoke admin rights form {memberName}?',
        196: 'Are you sure your want to grant admin rights to {memberName}?',
        197: 'Are you sure you want to remove the member {memberName}?',
        198: 'User group not found',
        199: 'User not found',
        200: 'Description',
        201: 'User group',
        202: 'Activity log',
        204: 'Failed to save user group.',
        205: 'Region remove',
        206: 'Region removed successfully.',
        207: 'Cannot remove region.',
        208: 'Cannot remove region. Please check your network connection and try again',
        209: 'Show lead preview',
        301: 'Add',
        302: 'Search project',
        303: 'Add new project',
        304: 'Select a project to view its details',
        305: 'You do not have enough permissions to edit this project.',
        319: 'Are you sure you want to remove {title} from project {projectTitle}?',
        323: 'Update',
        324: 'Revert',
        331: 'Enter project description',
        333: 'Enter project start date',
        334: 'End date',
        335: 'Enter project end date',
        336: 'Regions',
        337: 'Select regions',
        338: 'User groups',
        339: 'Select user groups',
        341: 'Search regions',
        342: 'Add region',
        343: 'There are no regions in this project.',
        344: 'Create new region',
        345: 'Use existing regions',
        346: 'Region title',
        347: 'e.g. Nepal',
        348: 'Code',
        349: 'e.g. NPL',
        350: 'ID',
        351: 'Remove region',
        352: 'Clone & edit',
        354: 'Are you sure you want to clone {title}?',
        357: 'Search analysis framework',
        358: 'Add new analysis framework',
        359: 'There are no analysis frameworks.',
        360: 'Saved',
        361: 'e.g. ACAPS framework',
        362: 'Use',
        363: 'Edit',
        365: 'Are you sure you want to use {title}?',
        366: 'If you use this analysis framework, you will recieve updates when the owner updates it.',
        369: 'e.g. ACAPS category editor',
        370: 'Search category editor',
        371: 'Add new category editor',
        372: 'There are no category editors.',
        373: 'If you use this category editor, you will recieve updates when the owner updates it.',
        374: 'After cloning and editing this category editor, you will not recieve any updates made by owner.',
        377: 'General details',
        378: 'Region details',
        379: 'Analysis framework',
        380: 'Category editor',
        401: 'Category',
        402: 'Select category',
        403: 'Add category',
        404: 'Edit category',
        405: 'Delete category',
        406: 'Nothing here',
        408: 'e.g. Sector, Affected groups, etc.',
        410: 'Ok',
        411: 'e.g. Wash',
        413: 'e.g. Wash stands for Water, Sanitation and Hygiene',
        414: 'Add new sub-category',
        415: 'Add new word',
        416: 'Word',
        417: 'e.g. people affected',
        418: 'Sub-Category details',
        419: 'Remove',
        420: 'Number of words:',
        421: 'No words yet',
        422: 'Add word manually',
        423: 'Document',
        424: 'Simplified',
        425: 'Extracted words',
        426: 'Select from gallery',
        427: 'Apply',
        428: 'Are you sure you want to delete category {category}?',
        429: 'Are you sure you want to delete subcategory {subcategory}?',
        500: 'Server error',
        501: 'Failed connecting to server',
        502: 'NLP',
        504: 'It\'s accurate',
        505: 'It\'s not accurate',
        506: 'Show suggestions for :',
        508: 'Entities',
        509: 'Go to overview',
        511: 'Go to list',
        512: 'Entry',
        513: 'There was a problem while fetching leads.',
        514: 'Excerpt',
        515: 'Format excerpt',
        517: 'Assisted',
        518: 'Original',
        519: 'Images',
        521: 'Select an excerpt',
        522: 'Add entry',
        523: 'Mark current entry for removal',
        525: 'Unmark current entry for removal',
        528: 'Clear',
        530: 'Edit entries',
        531: 'Set',
        533: 'Select geo region',
        534: 'Couldn\'t load geo options',
        535: 'Select locations',
        537: 'Search excerpt',
        538: 'Created by',
        540: 'NER',
        541: 'Assited tagging feedback',
        542: 'Thank you for your feedback.',
        543: 'Oops! It seems you don\'t have any entries. Please go back to the overview page to add some entries.',
        545: 'Locations',
        546: 'Much like all living beings, DEEP has evolved and has a growing brain. Right now, it can help give you recommendations on finding excerpts in your source that talk about the following sectors:\nWASH, Livelihood, Food, Protection, Shelter, NFI, Health, Nutrition, Education, Crosscutting, Agriculture, Logistic\n \nBut DEEP needs your help to learn! By hovering over a highlighted sentence, you will see the option to give a recommendation a thumbs up or thumbs down. Your feedback will help make DEEP’s recommendations more accurate for yourself and everyone else.\n \nContent available in the Category Editor will also be highlighted with this feature when you select \'Category Editor\' in list in the bottom right.\n \nSee something you don\'t like or want to leave feedback? Or just want somebody to talk to? Use the \'Feedback / Report a bug\' feature at the bottom of the screen and the DEEP itself will get back to you.',
        600: 'Export',
        601: 'Show preview',
        602: 'Start export',
        603: 'DOCX',
        604: 'PDF',
        605: 'XLXS',
        606: 'JSON',
        609: 'Entry attributes',
        610: 'Lead attributes',
        620: 'View all exports',
        621: 'User exports',
        622: 'Unable to load your previous exports.',
        623: 'Doc. type',
        624: 'Exported at',
        627: 'Export type',
        628: 'Download',
        629: 'Pending',
        630: 'Error',
        631: 'Completed',
        632: 'Recent exports',
        633: 'Go back to exports',
        634: 'Decoupled entries',
        635: 'Note that by selecting this option, it can greatly increase the amount of time to generate the export.',
        636: 'Disaggregate data for any list values (i.e. multiple administrative areas or multiple select fields).',
        637: 'Your export has been started.\nPlease go to view all exports page for further information on export.',
        638: 'You don\'t have any matrices in your analysis framework.',
        639: 'Report structure',
        640: 'No export options available',
        641: 'Leads',
        642: 'Couldn\'t load leads',
        643: 'Select',
        644: 'Unselect',
        646: 'Couldn\'t load project',
        648: 'Couldn\'t load analysis framework',
        649: 'Uncategorized',
        704: 'Date',
        705: 'Date range',
        706: 'Text or image excerpt',
        707: 'Time',
        709: 'Geo location',
        713: 'Geo area',
        718: 'Matrix 1D',
        719: 'Add / edit cell',
        720: 'Add cell',
        721: 'Edit row',
        722: 'Add row',
        723: 'Matrix 2D',
        724: 'Dimension-Y',
        726: 'Dimension-X',
        733: 'Tooltip',
        737: 'Multiselect',
        738: 'Option',
        739: 'e.g. Context',
        740: 'Edit multiselect',
        741: 'Add option',
        742: 'Number matrix',
        744: 'e.g. Row',
        745: 'e.g. Its a tooltip',
        746: 'e.g. Column',
        747: 'Edit number matrix',
        748: 'Rows',
        749: 'Add row unit',
        750: 'Columns',
        751: 'Add column unit',
        752: 'Number',
        753: 'Organigram',
        754: 'Organ',
        755: 'Edit organigram',
        757: 'Scale',
        758: 'e.g. Reliable',
        759: 'Edit scales',
        760: 'Add scale unit',
        763: 'e.g. Overview',
        764: 'Color',
        766: 'Add child',
        767: 'Remove element',
        768: 'e.g. 123 456',
        773: 'Edit title',
        775: 'Options',
        777: 'Information date',
        778: 'Exit',
        779: 'Default?',
        780: 'List',
        781: 'Overview',
        782: 'Untitled dimension',
        786: 'Subdimensions',
        788: 'Add subdimension',
        789: 'Add dimension',
        792: 'Edit matrix-2d',
        803: 'Welcome to DEEP (BETA)',
        805: 'Login with HID',
        806: 'Or',
        808: 'Password',
        809: 'Forgot password?',
        810: 'Do not have an account yet?',
        811: 'Register',
        812: 'Check your inbox: {email}',
        813: 'john.doe@mail.com',
        814: 'Login',
        817: 'Go back to login',
        818: 'Thank you for signing up. Please check your email {email} to set your password.',
        819: 'John',
        821: 'Doe',
        823: 'Togglecorp',
        825: 'Already have an account?',
        826: 'Submit',
        870: 'Error 404',
        871: 'Oops! You have come too DEEP',
        872: 'This is where the DEEP Kraken rests',
        873: 'Go to DEEP',
        875: 'Welcome to the',
        876: 'DEEP',
        877: 'Seems like you do not have any projects yet.',
        878: 'To get started, create a project from your profile.',
        879: 'Go to your profile',
        893: 'Opps, you need to to verify you are a human',
        894: 'Verify you are a human',
        900: 'User profile edit',
        901: 'User edit successful',
        902: 'User edit failure.',
        903: 'User edit failure. Please check your network connection and try again',
        904: 'User group delete',
        905: 'User group successfully deleted',
        906: 'User group deletion failure',
        907: 'User group deletion failure. Please check your network connection and try again',
        908: 'User group add',
        909: 'User group successfully created',
        910: 'User group creation failure',
        911: 'User group creation failure. Please check your network connection and try again',
        912: 'User project delete',
        913: 'Project successfully deleted',
        914: 'Project deletion failure',
        915: 'Project deletion failure. Please check your network connection and try again',
        916: 'User project add',
        917: 'Project successfully created',
        918: 'Project creation failure',
        919: 'Project creation failure. Please check your network connection and try again',
        920: 'Add user membership ',
        921: 'User added successfully ',
        924: 'Remove user membership',
        925: 'User removed successfully ',
        926: 'Cannot remove user',
        927: 'Cannot remove user. Please check your network connection and try again',
        928: 'Membership role',
        929: 'User role successfully updated',
        930: 'User role update failure.',
        931: 'Cannot update user role. Please check your network connection and try again',
        932: 'User group edit',
        933: 'Name updated successfully',
        937: 'Country delete successful',
        938: 'Cannot delete country.',
        939: 'Cannot delete country. Please check your network connection and try again',
        940: 'Add country',
        941: 'Country added successfully',
        942: 'Cannot add country.',
        943: 'Cannot add country. Please check your network connection and try again',
        948: 'Delete admin level',
        949: 'Admin level successfully deleted',
        950: 'Cannot delete admin level.',
        951: 'Cannot delete admin level. Please check your network connection and try again',
        953: 'Admin level successfully added',
        954: 'Cannot add admin level.',
        955: 'Cannot add admin level. Please check your network connection and try again',
        956: 'Edit admin level',
        957: 'Admin level successfully updated',
        960: 'Project details',
        961: 'Project details successfully updated',
        962: 'Cannot update project details.',
        963: 'Cannot update project details. Please check your network connection and try again',
        965: 'Analysis framework successfully added',
        966: 'Cannot add analysis framework.',
        967: 'Cannot add analysis framework. Please check your network connection and try again',
        968: 'Analysis framework form',
        969: 'Analysis framework form updated',
        970: 'Cannot update analysis framework form.',
        971: 'Cannot update analysis framework form. Please check your network connection and try again',
        972: 'Save lead',
        973: 'Lead save successful',
        974: '{errorCount} lead(s) could not be saved.',
        977: 'Lead successfully deleted',
        978: 'Lead fIle not found',
        979: 'Lead delete failed. Please check your network connection and try again',
        981: 'Analysis framework was updated in server.',
        982: 'Your copy was overridden by server\'s copy',
        983: 'Successfully saved the framework.',
        984: 'Category editor was updated in server.',
        985: 'Invalid drop source',
        986: 'Drag and drop are only valid from extracted words.',
        987: 'Some entries were updated in server.',
        988: 'Save entry',
        989: 'Entries successfully saved',
        990: '{errorCount} entries could not be saved.',
        993: 'Lead successfully removed',
        994: 'Remove leads',
        995: 'Leads successfully removed',
        996: 'Region details were updated in server.',
        997: 'Region details successfully saved.',
        998: 'Save region',
        999: 'There was an error while fetching existing users',
        1000: 'to',
        1001: 'Max value',
        1002: 'Min value',
        1200: 'User',
        1206: 'Search gallery files',
        1209: 'Loading file',
        1210: 'Open dropbox chooser',
        1211: 'Open google chooser',
        1214: 'Map not available',
        1217: 'Anon',
        1219: 'Select event',
        1220: 'Admin panel',
        1221: 'Logout',
        1222: 'Locating the required gigapixels to render ...',
        1223: 'Programming the flux capacitor ...',
        1224: 'Shovelling coal into the server ...',
        1225: 'Spinning up the hamster ...',
        1226: 'Checking the gravitational constant in your locale ...',
        1227: 'The server is powered by a lemon and two electrodes ...',
        1228: 'Don\'t think of purple hippos ...',
        1229: 'Dividing eternity by zero, please be patient...',
        1230: 'Photographing cats... Attaching signs... MEME complete ...',
        1231: 'Nobody exists on purpose, nobody belongs anywhere ...',
        1232: 'Swapping time and space...',
        1233: 'Greetings earthling! ...',
        1234: 'I am mr. Meeseeks! Look at me ...',
        1235: 'Oh, yeaah! You gotta get schwifty. ...',
        1236: 'Shhhh! The Kraken is sleeping ...',
        1237: 'BETA',
        1238: 'ALPHA',
        1239: 'NIGHTLY',
        1240: 'DEV',
        1300: 'Are you sure you want to leave? You may lose your unsaved changes.',
        1301: 'Oops! File not found',
        1302: 'Upload file',
        1928: 'Failed to update users list. Please check your network connection and try again',
        1929: 'Notifications',
        1930: '{requestedBy} requested to join the project {project}.',
        1932: '{requestedBy}\'s request to join the project {project} was accepted by {respondedBy}.',
        1933: '{requestedBy}\'s request to join the project {project} was rejected by {respondedBy}.',
        1934: 'Project join response',
        1935: 'Project join failure',
        1937: 'Reject',
        1938: 'Add as admin',
        1939: '{requestedBy} was added to the {project} as admin by {respondedBy}.',
        2000: 'Browser extension',
        2001: 'Your extension has been successfully set up.',
        2002: 'An error occured while setting up the extension. Please make sure you have installed and enabled the extension.',
        2003: 'Do you want to apply this value to all leads?',
        2004: 'Do you want to apply this value to all leads below?',
        2005: 'Do you want to apply this value to all entries?',
        2006: 'Do you want to apply this value to all entries below?',
        2007: 'Discard',
        2008: 'No GEO file uploaded.',
        2009: 'GEO file',
        2010: 'Something went wrong with loading this page. Please logout and try again.',
        2011: 'Widget has failed!',
        2012: 'Component has failed!',
        5550: '{count} items selected',
        5551: 'Selected',
        5552: 'All',
        5553: 'Filtered',
        5556: 'Invalid file(s) selected.',
        5557: 'File selection',
        5558: 'Password reset',
        5559: 'Home',
        5560: 'Dashboard',
        5561: 'Leads visualization',
        5562: 'Assessments',
        5563: 'Edit assessment',
        5566: 'User profile',
        5569: 'Weekly snapshot',
        5570: 'Api docs',
        5571: '404',
        5572: 'String management',
        6000: 'Do you want to remove this widget?',
        7001: 'Metadata',
        7002: 'Methodology',
        7003: 'Summary',
        7004: 'Score',
        7036: 'Response schema',
        7037: 'Request schema',
        7038: 'Loading api',
        7039: 'Subsectors',
        7040: 'Untitled row',
        7041: 'No row selected',
        7042: 'Project members',
        7500: 'Couldn\'t upload image',
        7501: 'Couldn\'t upload file',
        8101: 'Delete this assessment',
        8102: 'Edit this assessment',
        8501: 'Select a source to add new lead',
        1003: 'Failed to save region detail.',
        1004: 'Please wait while we process the text for this lead. It can take some time depending on the size of the lead.',
        251: 'DEEP supports .json, .geojson and shapefiles compressed in .zip',
        800: 'Show clustering',
        801: 'Show visualization',
        802: 'Mark as pending',
        804: 'Mark as processed',
        1999: 'leads per page',
        7634: 'Projects per page',
        7000: 'Do you want to mark the lead as pending?',
        8001: 'Do you want to mark the lead as processed?',
        8002: 'Are you sure you want to continue?',

        8050: 'Failed to change lead status.',
        8051: 'Lead status changed successfully.',

        8060: 'Chord diagram',
        8061: 'Collapsible tree view',
        8062: 'Correlation matrix',
        8063: 'Forced directed graph',
        8064: 'Keyword correlation',
        8065: 'Radial dendogram',
        8066: 'Sunburst',
        8067: 'Topic correlation',
        8068: 'Topic modeling',
        8069: 'Tree map',
        8070: 'Show table',
        8071: 'No leads found',
        8072: 'Try with different fitlers',
        8073: 'Failed to get keyword correlation',
        8074: 'Failed to get NER',
        8075: 'Failed to get topic correlation',
        8076: 'Failed to get topic modeling',

        253: 'Under construction',

        1005: 'Edit entries',
        1006: 'No of entries',
        9000: 'Priority humanitarian access issues',
        9001: 'Settings facing most humanitarian access issues',
        9002: 'Population with limited/intermittent access',
        9003: 'Population with no/restricted access',
        9004: 'Population with humanitarian access constraints',
        9005: 'Sectors with most unmet needs',
        9006: 'Priority affected groups',
        9007: 'Priority group with specific needs',
        9008: 'Population in moderate need of assistance (not life threatening) (do not know)',
        9009: 'Population in severe need of assistance (life threatening) (do not know)',
        9010: 'Population in need of assistance (do not know)',
        9011: '1',
        9012: '2',
        9013: '3',
        9014: 'Population in moderate need of assistance (not life threatening)',
        9015: 'Population in severe need of assistance (life threatening)',
        9016: 'Population in need of assistance',
        9017: 'Select at least 3 sectors in methodology',
        9018: 'Cross sector',
        9019: 'Humanitarian access',

        9020: 'Basic information',
        9021: 'Additional documents',
        9022: 'Executive summary',
        9023: 'Assessment database',
        9024: 'Questionnaire',

        9025: 'Focuses',
        9026: 'Sectors',
        9027: 'Affected groups',
        9028: 'Locations',
        9029: 'Methodology content',

        9030: 'Objectives',
        9031: 'Data collection techniques',
        9032: 'Sampling',
        9033: 'Limitations',
        9034: 'Attributes',

        9035: 'Drag and drop objectives here',
        9036: 'Drag and drop data collection techniques here',
        9037: 'Drag and drop sampling (site and respondent selection) here',
        9038: 'Drag and drop limitations here',
        9039: 'Main sectoral outcomes',
        9040: 'Main sectoral underlying factors',


        9919: 'Select',
        9920: 'Report this error',

        1100: 'Connectors',
        1101: 'Search connectors',
        1102: 'Add connector',
        1103: 'Gotham daily',
        1104: 'Source type',
        1105: 'RSS feed',
        1106: 'Connector create',
        1107: 'Connector was successfully created.',
        1109: 'Connector sources',
        1110: 'There was a problem while fetching connector sources.',
        1111: 'Select a connector to view its detail.',
        1112: 'There was a problem while fetching connector.',
        1113: 'Connectors',
        1114: 'The connector you are looking for does not exist.',
        1115: 'There are no connectors.',
        1116: 'Failed to patch connector.',
        1117: 'Connector details were saved successfully.',
        1118: 'Failed to create connector.',
        1119: 'Users',
        1120: 'Visibility',
        1121: 'Set it to local',
        1122: 'Set it to global',
        1123: 'You need project admin rights to change this setting.',
        1124: 'Remove project',
        1125: 'Failed to fetch projects',
        1126: 'Failed to save project.',
        1127: 'Failed to create new category editor.',
        1128: 'Failed to create new framework.',
        1129: 'Group',
        1130: 'Progress reports of June',
        1131: 'Add lead group',
        1132: 'Failed to create lead group',
        1133: 'Lead group',
        1134: 'Lead group created successfully.',
        1135: 'Test',
        1136: 'This url is already added.',
        1137: 'Failed to test connector.',
        1138: 'Test results',
        7627: 'Admins',
        7628: 'Discover usergroups',
        7629: 'Discover projects',
        7630: 'Leads activity',
        7631: 'Entries activity',
        7632: 'Discover',
        11000: 'Lead groups',
        11001: 'Show lead groups',
        11002: 'No of leads',
        11003: 'Lead group deleted successfully.',
        11004: 'Are you sure you want to delete this lead group?',
        11005: 'Show leads',
        11006: 'Failed to delete lead group.',
        2999: 'clusterVisualization',
        3000: 'Cluster visualization',
        3001: 'Show table',
        3002: 'Score',
        3003: 'Title',
        3004: 'Cannot initialize cluster creation for project. Please check your network connection and try again',
        3005: 'Cannot fetch data for given cluster. Please check your network connection and try again',
        3006: 'Title',
        3007: 'Classified Doc Id',
        3008: 'Created At',
        3009: 'Showing {noOfClusters} clusters from {noOfLeads} leads',
        3010: 'Cluster-{clusterIndex}',
        3011: 'Keywords',
        3012: '{leadsCount} leads',
        3013: 'Leads',

        3999: 'Visualizations',
        4000: 'Visualization',
        4001: 'Sunburst',
        4002: 'Correlation matrix',
        4003: 'Dendrogram',
        4004: 'Radial dendrogram',
        4005: 'Treemap',
        4006: 'Zoomable treemap',
        4007: 'Chord diagram',
        4008: 'Horizontal bar',
        4009: 'Forced directed graph',
        4010: 'Force directed graph voronoi',
        4011: 'Collapsible tree',
        4012: 'Orgchart',
        4013: 'Piechart',
        4014: 'Donutchart',
        4015: 'Organigram',
        4016: 'Stacked barchart',
        4017: 'Streamgraph',
        4018: 'Sankey',
        4019: 'Sparklines',
        4020: 'Parallel coordinates',

        12000: 'Goto edit entries page for the lead',
    },
    links: {
        /*
           'acorn.fruits': {
           appleLabel: 98161,
           ballLabel: 98162,
           mangoLabel: 98163,
           orangeLabel: 98164,
           },
         */

        browserExtension: {
            browserExtensionSuccessTitle: 2000,
            browserExtensionSuccessMessage: 2001,
            browserExtensionFailureTitle: 2000,
            browserExtensionFailureMessage: 2002,
        },
        'discoverProjects.table': {
            titleTitle: 13,
            descriptionTitle: 200,
            createdAtTitle: 163,
            createdByTitle: 538,
            adminsTitle: 7627,
            frameworkTitle: 379,
            regionsTitle: 336,
            numberOfUsersTitle: 1119,
            numberOfLeadsTitle: 641,
            numberOfEntriesTitle: 15,
            leadsActivityTitle: 7630,
            entriesActivityTitle: 7631,
            statusTitle: 8,
            actionsTitle: 16,
        },
        'discoverProjects.filter': {
            status: 8,
            projects: 173,
            placeholderAny: 14,
            placeholderSearch: 9,
            filterApplyFilter: 10,
            filterClearFilter: 11,
        },
        'discoverProjects.footer': {
            projectsPerPage: 7634,
        },
        framework: {
            analysisFramework: 379,
            headerList: 780,
            headerOverview: 781,
            gotoListButtonLabel: 511,
            saveButtonLabel: 25,
            gotoOverviewButtonLabel: 509,
            exitButtonLabel: 778,
            confirmDeletewWidget: 6000,

            // notification
            afTitle: 379,
            afUpdate: 981,
            afUpdateOverridden: 982,
            afSaveSuccess: 983,
        },
        'framework.timeWidget': {
            widgetTitlePlaceholder: 13,

            titleLabel: 13,
            saveButtonLabel: 25,
            cancelButtonLabel: 61,
            editTitleModalHeader: 773,
        },
        'framework.dateWidget': {
            informationDateCheckboxLabel: 777,
            widgetTitlePlaceholder: 13,

            titleLabel: 13,
            saveButtonLabel: 25,
            cancelButtonLabel: 61,
            editTitleModalHeader: 773,
        },
        'framework.dateRangeWidget': {
            widgetTitlePlaceholder: 13,
            dateRangeToLabel: 1000,

            titleLabel: 13,
            saveButtonLabel: 25,
            cancelButtonLabel: 61,
            editTitleModalHeader: 773,
        },
        'framework.excerptWidget': {
            formatExcerpt: 515,
            textOrImageExcerptWidgetLabel: 706,
            altEntryLabel: 512,

            widgetTitlePlaceholder: 13,
            titleLabel: 13,
            saveButtonLabel: 25,
            cancelButtonLabel: 61,
            editTitleModalHeader: 773,
        },
        'framework.geoWidget': {
            geoAreaButtonLabel: 713,

            widgetTitlePlaceholder: 13,
            titleLabel: 13,
            saveButtonLabel: 25,
            cancelButtonLabel: 61,
            editTitleModalHeader: 773,
        },
        'framework.multiselectWidget': {
            editMultiselectModalTitle: 740,
            addOptionButtonLabel: 741,
            optionLabel: 738,
            optionPlaceholder: 739,
            optionsHeader: 775,

            titlePlaceholderScale: 758,
            titleLabel: 13,
            saveButtonLabel: 25,
            cancelButtonLabel: 61,
        },
        'framework.selectWidget': {
            editSelectModalTitle: 740,
            addOptionButtonLabel: 741,
            optionLabel: 738,
            optionPlaceholder: 739,
            optionsHeader: 775,

            titlePlaceholderScale: 758,
            titleLabel: 13,
            saveButtonLabel: 25,
            cancelButtonLabel: 61,
        },
        'framework.numberMatrixWidget': {
            editNumberMatrixModalTitle: 747,
            tooltipTitle: 733,
            tooltipPlaceholder: 745,
            addColumnUnitButtonLabel: 751,
            titlePlaceholderRow: 744,
            titlePlaceholderColumn: 746,
            addRowUnitButtonLabel: 749,
            rowsLabel: 748,
            columnsLabel: 750,
            numberPlaceholder: 768,
            titleLabel: 13,

            numberMatrixWidgetLabel: 742,
            titlePlaceholderScale: 758,
            saveButtonLabel: 25,
            cancelButtonLabel: 61,
        },
        'framework.numberWidget': {
            widgetTitlePlaceholder: 13,
            titleLabel: 13,
            saveButtonLabel: 25,
            cancelButtonLabel: 61,
            editTitleModalHeader: 773,
            numberPlaceholder: 768,
            maxValueLabel: 1001,
            minValueLabel: 1002,
        },
        'framework.organigramWidget': {
            organPlaceholder: 754,
            editOrganigramModaltitle: 755,
            organigramWidgetLabel: 753,
            addChildButtonTitle: 766,
            applyButtonLabel: 427,
            removeElementButtonTitle: 767,

            saveButtonLabel: 25,
            cancelButtonLabel: 61,
            titleLabel: 13,
            titlePlaceholderScale: 758,
        },
        'framework.scaleWidget': {
            editScaleModalTitle: 759,
            addscaleUnitButtonLabel: 760,
            titlePlaceholderScale: 758,
            colorLabel: 764,
            defaultButtonLabel: 779,

            saveButtonLabel: 25,
            cancelButtonLabel: 61,
            titleLabel: 13,
        },
        'framework.matrix1dWidget': {
            saveButtonLabel: 25,
            cancelButtonLabel: 61,
            titleLabel: 13,
            matrix1DWidgetLabel: 718,
            optionPlaceholder: 739,
            titlePlaceholderScale: 758,
            tooltipTitle: 733,
            tooltipPlaceholder: 745,
            colorLabel: 764,

            addRowButtonLabel: 722,
            titlePlaceholderOverview: 763,
            untitledRowTitle: 7040,
            matrix1DModalTitle: 719,
            addCellButtonLabel: 720,
            editRowModalTitle: 721,
            noRowSelected: 7041,
        },
        'framework.matrix2dWidget': {
            matrix2DWidgetLabel: 723,
            tooltip: 733,
            saveButtonTitle: 25,
            cancelButtonTitle: 61,
            dimensionXLabel: 726,
            dimensionYLabel: 724,
            untitledDimensionTitle: 782,
            subdimensions: 786,
            addSubdimensionButtonTitle: 788,
            addDimensionButtonTitle: 789,
            empty: 406,
            title: 13,
            subsectorsLabel: 7039,
            editModalTitle: 792,
            color: 764,
        },
        api: {
            loadingLabel: 7038,
            responseSchemaLabel: 7036,
            requestSchemaLabel: 7037,
        },
        categoryEditor: {
            saveCeButtonLabel: 25,
            headerCategoryLabel: 401,
            selectCategoryPlaceholder: 402,
            addCategoryTooltip: 403,
            editCategoryTooltip: 404,
            deleteCategoryTooltip: 405,
            nothingHereText: 406,
            subCategoryDetailsText: 418,
            removeCategoryButtonLabel: 419,
            subCategoryTitleLabel: 13,
            subCategoryTitlePlaceholder: 408,
            subCategoryDescriptionLabel: 200,
            subCategoryDescriptionPlaceholder: 413,
            numberOfWordsLabel: 420,
            noWordsText: 421,
            addWordManuallyButtonLabel: 422,
            documentTabLabel: 423,
            simplifiedTabLabel: 424,
            ngramsTabLabel: 425,
            selectFromGalleryButtonLabel: 426,
            applyButtonLabel: 427,
            titleLabel: 13,
            confirmTextDeleteCategory: 428,
            confirmTextDeleteSubCategory: 429,
            exitButtonLabel: 778,
            addSubcategory: 139,

            // notification
            ceUpdate: 984,
            ceUpdateOverridden: 982,
            invalidDropSource: 985,
            validDropAlert: 986,
        },
        'categoryEditor.newCategory': {
            addCategoryTitleLabel: 13,
            addCategoryTitlePlaceholder: 408,
            addCategoryTooltip: 403,
            editCategoryTooltip: 404,
            modalCancel: 61,
            modalOk: 410,
        },
        'categoryEditor.newSubcategory': {
            addNewSubCategoryModalTitle: 414,
            addSubCategoryTitleLabel: 13,
            addSubCategoryTitlePlaceholder: 411,
            addSubCategoryDescriptionLabel: 200,
            addSubCategoryDescriptionPlaceholder: 413,
            modalCancel: 61,
            modalOk: 410,
        },
        'categoryEditor.newNgram': {
            addNewWordModalTitle: 415,
            addNewWordLabel: 416,
            addNewWordPlaceholder: 417,

            modalCancel: 61,
            modalOk: 410,
        },
        'components.appLoading': {
            loadingMessages1: 1222,
            loadingMessages2: 1223,
            loadingMessages3: 1224,
            loadingMessages4: 1225,
            loadingMessages5: 1226,
            loadingMessages6: 1227,
            loadingMessages7: 1228,
            loadingMessages8: 1229,
            loadingMessages9: 1230,
            loadingMessages10: 1231,
            loadingMessages11: 1232,
            loadingMessages12: 1233,
            loadingMessages13: 1234,
            loadingMessages14: 1235,
            loadingMessages15: 1236,
        },
        'components.appError': {
            problemText: 2010,
            reportErrorTitle: 9920,
        },
        'components.widgetError': {
            problemText: 2011,
            reportErrorTitle: 9920,
        },
        'components.vizError': {
            problemText: 2012,
            reportErrorTitle: 9920,
        },
        'components.componentError': {
            problemText: 2012,
            reportErrorTitle: 9920,
        },
        'components.externalGallery': {
            gatheringWebsiteInfoLabel: 49,
        },
        'components.galleryImage': {
            altUser: 1200,
        },
        'components.galleryViewer': {
            cannotPreviewUrl: 28,
            invalidUrl: 30,
        },
        'components.internalGallery': {
            loadingFileLabel: 1209,
            deepFileNotFound: 1301,
        },
        'components.deepGallerySelect': {
            select: 643,
            unselect: 644,
            tableHeaderSelect: 643,
            tableHeaderType: 21,
            tableHeaderName: 103,
            tableHeaderDateCreated: 2,
            searchGalleryLabel: 9,
            searchGalleryPlaceholder: 1206,
            cancelButtonLabel: 61,
            addButtonLabel: 301,
            uploadFileButtonLabel: 1302,
        },
        'components.dropboxChooser': {
            openDropboxChooserText: 1210,
        },
        'components.googlePicker': {
            openGoogleChooserText: 1211,
        },
        'components.editAdminLevel': {
            noFileUploadedLabel: 2008,
            geoFileLabel: 2009,
            cancelButtonLabel: 61,
            saveChangesButtonLabel: 62,
            adminLevelLabel: 89,
            adminLevelPlaceholder: 89,
            adminLevelNameLabel: 90,
            adminLevelNamePlaceholder: 91,
            namePropertyPlaceholder: 93,
            pcodePropertyPlaceholder: 95,
            parentNamePropPlaceholder: 97,
            parentAdminLevelPlaceholder: 99,
            parentCodePropPlaceholder: 99,
            parentAdminLevelLabel: 100,
            loadGeoShapeFile: 125,
            geoshapeTooltip: 251,
            namePropertyLabel: 92,
            parentNamePropLabel: 96,
            parentCodePropLabel: 98,
            pcodePropertyLabel: 94,

            // notification
            adminLevelCreate: 87,
            adminLevelCreateSuccess: 953,
            adminLevelCreateFailure: 954,
            adminLevelCreateFatal: 955,
            adminLevelEdit: 956,
            adminLevelEditSuccess: 957,
            invalidFileSelection: 5556,
            fileSelection: 5557,
        },
        'components.navbar': {
            deepLabel: 876,
            betaLabel: 1237,
            alphaLabel: 1238,
            nightlyLabel: 1239,
            devLabel: 1240,
            selectEventPlaceholder: 1219,
            adminPanelLabel: 1220,
            logoutLabel: 1221,
            anonymousLabel: 1217,
        },
        common: {
            underConstructionLabel: 253,
            youHaveUnsavedChanges: 1300,
        },
        countries: {
            countriesLabel: 51,
            searchCountryPlaceholer: 52,
            addCountryButtonLabel: 301,
            addCountryModalHeaderLabel: 53,
            deleteCountryButtonLabel: 54,
            deleteCountryConfirm: 55,
            generalTabLabel: 56,
            keyFiguesTabLabel: 57,
            populationTabLabel: 58,
            seasonalTabLabel: 59,
            mediaTabLabel: 60,
            saveButtonLabel: 25,
            discardButtonLabel: 2007,
            humanDevelopmentIndexLabel: 63,
            underFiveMortalityLabel: 64,
            uprootedPeopleLabel: 65,
            informScoreLabel: 66,
            indexLabel: 67,
            geoRankLabel: 68,
            geoScoreLabel: 69,
            rankLabel: 70,
            u5mLabel: 71,
            numberOfRefugeesLabel: 72,
            percentageUprootedPeopleLabel: 73,
            numberIdpLabel: 74,
            numberReturnedRefugeesLabel: 75,
            riskClassLabel: 76,
            informRiskIndexLabel: 77,
            hazardAndExposureLabel: 78,
            vulnerabilityLabel: 79,
            lackOfCopingCapacityLabel: 80,
            noCountriesText: 117,
            selectCountryText: 118,
            countryNotFoundText: 119,
            regionPatchErrorText: 1003,

            // notification
            countryDelete: 54,
            countryDeleteSuccess: 937,
            countryDeleteFailure: 938,
            countryDeleteFatal: 939,
            regionUpdate: 996,
            regionUpdateOverridden: 982,
            regionSave: 998,
            regionSaveSuccess: 997,
        },
        'components.geoSelection': {
            cancelGeoSelectionButtonLabel: 61,
            locationSelectPlaceholder: 535,
            locationSelectTitle: 545,
            regionSelectPlaceholder: 533,
            regionSelectTitle: 336,
            setGeoSelectionButtonLabel: 531,
        },
        'components.leadPreview': {
            previewNotAvailableText: 132,
        },
        'components.assistedTagging': {
            accurateTextTitle: 504,
            addEntryButtonLabel: 301,
            sourceText: 83,
            sourceNLP: 502,
            sourceCE: 380,
            sourceNER: 540,
            showSuggestionText: 506,
            serverErrorText: 500,
            assitedTaggingFeedbackTitle: 541,
            assitedTaggingFeedbackMessage: 542,
            ceLabel: 380,
            connectionFailureText: 501,
            entitiesLabel: 508,
            nlpLabel: 502,
            notAccurateTextTitle: 505,
            infoTooltip: 546,
        },
        editEntry: {
            gotoOverviewButtonLabel: 509,
            saveButtonLabel: 25,
            gotoListButtonLabel: 511,
            altLabel: 512,
            simplifiedTabLabel: 424,
            assistedTabLabel: 517,
            originalTabLabel: 518,
            tabularTabLabel: 142,
            imagesTabLabel: 519,
            entriesTabLabel: 15,
            unrecognizedLeadMessage: 140,
            selectExcerptPlaceholder: 521,
            addEntryButtonTitle: 522,
            removeEntryButtonTitle: 523,
            undoRemoveEntryButtonTitle: 525,
            noEntryFound: 543,
            applyAllButtonTitle: 130,
            applyAllBelowButtonTitle: 131,
            applyToAll: 2005,
            applyToAllBelow: 2006,

            // notification
            entryUpdate: 987,
            entryUpdateOverridden: 982,
            entrySave: 988,
            entrySaveSuccess: 989,
            entrySaveFailure: 990,
        },
        'editEntry.widgets': {
            dateRangeToLabel: 1000,
        },
        editAssessment: {
            metadataTabLabel: 7001,
            methodologyTabLabel: 7002,
            summaryTabLabel: 7003,
            scoreTabLabel: 7004,
            noAryTemplateForProject: 144,
            geoOptionsFatalMessage: 534,
            simplifiedTabLabel: 424,
            assistedTabLabel: 517,
            originalTabLabel: 518,
            tabularTabLabel: 142,
            imagesTabLabel: 519,
            entriesTabLabel: 15,
            unrecognizedLeadMessage: 140,
        },
        'editAssessment.entriesListing': {
            altLabel: 512,
            editEntriesText: 1005,
            noOfEntriesText: 1006,
        },
        entries: {
            applyFilterButtonLabel: 427,
            clearFilterButtonLabel: 528,
            editEntryLinkTitle: 12000,
            editEntryButtonLabel: 530,
            searchFilterLabel: 9,
            searchFilterPlaceholder: 537,
            createdByFilterLabel: 538,
            createdAtFilterLabel: 163,
            entriesTabLabel: 15,
            geoOptionsFatalMessage: 534,
        },
        'entries.widgets': {
            dateRangeToLabel: 1000,
        },
        export: {
            headerExport: 600,
            showPreviewButtonLabel: 601,
            startExportButtonLabel: 602,
            viewAllExportsButtonLabel: 620,
            docxLabel: 603,
            pdfLabel: 604,
            xlxsLabel: 605,
            jsonLabel: 606,
            entryAttributesLabel: 609,
            leadAttributesLabel: 610,
            createdAtLabel: 163,
            userExportsTitle: 621,
            userExportsFataMessage: 622,
            documentTypeHeaderLabel: 623,
            exportedAtHeaderLabel: 624,
            exportTitleHeaderLabel: 13,
            statusHeaderLabel: 8,
            exportTypeHeaderLabel: 627,
            exportDownloadHeaderLabel: 628,
            pendingStatusLabel: 629,
            errorStatusLabel: 630,
            completedStatusLabel: 631,
            userExportsHeader: 632,
            goBackToExportLabel: 633,
            decoupledEntriesLabel: 634,
            decoupledEntriesTitle: 635,
            decoupledEntriesTitle2: 636,
            exportStartedNotifyMessage: 637,
            noMatrixAfText: 638,
            noOptionsAvailable: 640,
            reportStructureLabel: 639,
            uncategorizedTitle: 649,
            leadsLabel: 641,
            cantLoadLeads: 642,
            selectLabel: 643,
            titleLabel: 13,
            projectLabel: 31,
            cantLoadProject: 646,
            afLabel: 379,
            cantLoadAf: 648,
        },
        fourHundredFour: {
            errorFourHundredFour: 870,
            message1: 871,
            message2: 872,
            goToDeep: 873,
        },
        homescreen: {
            welcomeText: 875,
            deepLabel: 876,
            message1: 877,
            message2: 878,
            goToProfile: 879,
        },
        assessments: {
            titleLabel: 13,
            createdAt: 163,
            tableHeaderActions: 16,
            aryDeleteConfirmText: 134,
            placeholderAnybody: 17,
            placeholderAnytime: 18,
            placeholderSearch: 9,
            filterDateCreated: 2,
            createdByFilterLabel: 538,
            filterApplyFilter: 10,
            filterClearFilter: 11,
            removeAryButtonTitle: 8101,
            editAryButtonTitle: 8102,
        },
        'editAssessment.metadata': {
            basicInformationTitle: 9020,
            additionalDocumentsTitle: 9021,
            executiveSummaryTitle: 9022,
            assessmentDatabaseTitle: 9023,
            questionnaireTitle: 9024,
        },
        'editAssessment.methodology': {
            focusesTitle: 9025,
            sectorsTitle: 9026,
            affectedGroupsTitle: 9027,
            locationsTitle: 9028,
            methodologyContentTitle: 9029,
            attributesTitle: 9034,
            objectivesTitle: 9030,
            dataCollectionTechniquesTitle: 9031,
            samplingTitle: 9032,
            limitationsTitle: 9033,

            objectivesPlaceholder: 9035,
            dataCollectionTechniquesPlaceholder: 9036,
            samplingPlaceholder: 9037,
            limitationsPlaceholder: 9038,
        },
        'editAssessment.summary': {
            priorityIssue: 9000,
            affectedLocation: 9001,
            limitedAccessPopulation: 9002,
            restrictedAccessPopulation: 9003,
            humanitarianAccessPopulation: 9004,
            prioritySectors: 9005,
            affectedGroups: 9006,
            specificNeedGroups: 9007,
            outcomes: 9039,
            underlyingFactors: 9040,
            moderateAssistancePopulationUnknown: 9008,
            severeAssistancePopulationUnknown: 9009,
            assistancePopulationUnknown: 9010,
            rank1Title: 9011,
            rank2Title: 9012,
            rank3Title: 9013,
            moderateAssistancePopulation: 9014,
            severeAssistancePopulation: 9015,
            assistancePopulation: 9016,
            crossSectorEmptyText: 9017,
            crossSectorTitle: 9018,
            humanitarianAccessTitle: 9019,
        },
        leads: {
            assigneeLabel: 6,
            assignee: 6,
            filterClearFilter: 11,
            filterSourceType: 21,
            filterStatus: 8,
            leads: 641,
            placeholderAny: 14,
            placeholderSearch: 9,
            filterDateCreated: 2,
            filterDatePublished: 3,
            filterConfidentiality: 7,
            filterApplyFilter: 10,
            filterClearSimilarFilter: 47,
            placeholderAnybody: 17,
            placeholderAnytime: 18,
            tableHeaderOwner: 1,
            tableHeaderDateCreated: 2,
            tableHeaderDatePublished: 3,
            tableHeaderConfidentiality: 7,
            tableHeaderPublisher: 5,
            tableHeaderNoOfEntries: 15,
            tableHeaderStatus: 8,
            tableHeaderActions: 16,
            addSourcesButtonLabel: 12,
            searchSimilarLeadButtonTitle: 135,
            editLeadButtonTitle: 136,
            removeLeadLeadButtonTitle: 137,
            addEntryFromLeadButtonTitle: 138,
            addAssessmentFromLeadButtonTitle: 143,
            leadDeleteConfirmText: 141,
            leadDeleteSuccess: 977,
            leadDeleteFailure: 979,
            leadDelete: 191,
            showViz: 801,
            showLeadGroups: 11001,
            showCluster: 800,
            markAsPendingTitle: 802,
            markAsProcessedTitle: 804,
            leadsPerPage: 1999,
            titleLabel: 13,
            leadConfirmText: 8002,
            leadMarkPendingConfirmText: 7000,
            leadMarkProcessedConfirmText: 8001,
            leadsGetFailure: 513,
            leadsPatchFailure: 8050,
            leadsPatchSuccess: 8051,
        },
        leadsViz: {
            chordDiagram: 8060,
            collapsibleTreeView: 8061,
            correlationMatrix: 8062,
            forcedDirectedGraph: 8063,
            keywordCorrelation: 8064,
            radialDendogram: 8065,
            sunburst: 8066,
            topicCorrelation: 8067,
            topicModeling: 8068,
            treeMap: 8069,
            showTable: 11005,
            leads: 641,
            leadsGetFailure: 513,
            noLeadsFoundHeader: 8071,
            noLeadsFoundDescription: 8072,
            ner: 540,
            keywordCorrelationGetFailure: 8073,
            nerGetFailure: 8074,
            topicCorrelationGetFailure: 8075,
            topicModelingFailure: 8076,
        },
        leadGroups: {
            leadGroupsTitle: 11000,
            leadGroupDeleteSuccess: 11003,
            leadGroupDeleteFailure: 11006,
            showLeads: 11005,
            titleLabel: 13,
            createdAt: 163,
            createdBy: 538,
            noOfLeadsTitle: 11002,
            tableHeaderActions: 16,
            leadGroupDeleteConfirmText: 11004,
            placeholderSearch: 9,
            filterApplyFilter: 10,
            filterClearFilter: 11,
        },
        addLeads: {
            leadGroupCreateFailure: 1132,
            fileUploadFailText: 7501,
            textLabel: 20,
            titleLabel: 13,
            datePublishedLabel: 3,
            projectLabel: 31,
            publisherLabel: 5,
            confidentialityLabel: 7,
            leadGroupLabel: 1129,
            assigneeLabel: 6,
            urlLabel: 32,
            websiteLabel: 33,
            selectInputPlaceholderLabel: 38,
            projectPlaceholderLabel: 39,
            titlePlaceHolderLabel: 40,
            urlPlaceholderLabel: 41,
            publisherPlaceHolderLabel: 43,
            datePublishedPlaceholderLabel: 44,
            textareaPlaceholderLabel: 45,
            sourcePreview: 48,
            applyAllButtonTitle: 130,
            applyAllBelowButtonTitle: 131,
            previewNotAvailable: 132,
            leadFileNotFound: 978,
            extractLead: 129,
            applyToAll: 2003,
            applyToAllBelow: 2004,
            noLeadsText: 8501,

            // notification
            leadGroupTitle: 1133,
            leadGroupCreateSuccess: 1134,
            leadSave: 972,
            leadSaveSuccess: 973,
            leadSaveFailure: 974,
            connectorGetFailure: 1112,
            connectorSourcesGetFailure: 1110,
            connectorSourcesTitle: 1109,
            connectorTitle: 1113,
        },
        'addLeads.actions': {
            deleteLeadConfirmText: 133,
            leadDiscard: 137,
            leadDiscardSuccess: 993,
            leadsDiscard: 994,
            leadsDiscardSuccess: 995,

            previousButtonLabel: 22,
            nextButtonLabel: 23,
            showLeadPreviewLabel: 209,

            removeAllButtonTitle: 5552,
            removeAllFilteredButtonTitle: 5553,
            removeAllCompletedButtonTitle: 360,
            removeButtonTitle: 419,
            removeCurrentButtonTitle: 5550,
            saveAllButtonTitle: 5552,
            saveAllFilteredButtonTitle: 5553,
            saveButtonTitle: 25,
            saveCurrentButtonTitle: 5551,
        },
        'addLeads.sourceButtons': {
            googleDriveLabel: 35,
            dropboxLabel: 36,
            localDiskLabel: 37,
            addSourceFromLabel: 34,
            connectorsLabel: 1100,
            textLabel: 20,
            websiteLabel: 33,

            // notification
            fileSelection: 5557,
            invalidFileSelection: 5556,
        },
        'addLeads.filters': {
            filterPublisher: 5,
            filterClearFilter: 11,
            filterSourceType: 21,
            filterStatus: 8,
            placeholderAny: 14,
            placeholderSearch: 9,
        },
        'addLeads.addLeadGroup': {
            modalAddLabel: 301,
            addLeadGroupTitleLabel: 13,
            addLeadGroupTitlePlaceholder: 1130,
            addLeadGroupModalTitle: 1131,
            modalCancelLabel: 61,
        },
        'addLeads.connectorsSelect': {
            selectedNumberText: 5550,
            noConnectorsLabel: 1115,
            leadAlreadyAdded: 1136,
            modalCancelLabel: 61,
            modalSelectLabel: 9919,
            connectorsLabel: 1100,
            searchConnectorPlaceholder: 1101,
            datePublishedLabel: 3,
            titleLabel: 13,
        },
        register: {
            checkYourEmailText: 818,
            firstNameLabel: 150,
            firstNamePlaceholder: 819,
            lastNameLabel: 152,
            lastNamePlaceholder: 821,
            organizationLabel: 154,
            organizationPlaceholder: 823,
            alreadyHaveAccountText: 825,
            emailLabel: 184,
            emailPlaceholder: 813,
            goBackToLoginText: 817,
            loginLabel: 814,
            registerLabel: 811,
            retryRecaptcha: 894,
        },
        passwordReset: {
            checkInboxText: 812,
            goBackToLoginText: 817,
            submitForgetPassword: 826,
            emailLabel: 184,
            emailPlaceholder: 813,
            retryRecaptcha: 894,
        },
        login: {
            welcomeToText: 803,
            logInWIthHid: 805,
            orText: 806,
            passwordLabel: 808,
            forgotPasswordText: 809,
            noAccountYetText: 810,
            emailLabel: 184,
            emailPlaceholder: 813,
            loginLabel: 814,
            registerLabel: 811,
            enterRecaptcha: 893,
            retryRecaptcha: 894,
        },
        widgetTitle: {
            dateWidgetLabel: 704,
            dateRangeWidgetLabel: 705,
            timeWidgetLabel: 707,
            excerptWidgetLabel: 514,
            geoWidgetLabel: 709,
            matrix1DWidgetLabel: 718,
            matrix2DWidgetLabel: 723,
            multiselectWidgetLabel: 737,
            selectWidgetLabel: 643,
            numberMatrixWidgetLabel: 742,
            numberWidgetLabel: 752,
            organigramWidgetLabel: 753,
            scaleWidgetLabel: 757,
        },
        pageTitle: {
            login: 814,
            register: 811,
            passwordReset: 5558,

            homeScreen: 5559,
            dashboard: 5560,

            discoverProjects: 7629,
            discoverUserGroups: 7628,
            leads: 641,
            leadsViz: 5561,
            leadGroups: 11000,
            addLeads: 12,
            entries: 15,
            arys: 5562,
            editAry: 5563,
            editLeadGroupAssessment: 5563,
            export: 600,

            editEntries: 1005,

            userProfile: 5566,
            userGroup: 201,
            adminPanel: 1220,
            countries: 51,
            projects: 173,
            connectors: 1100,

            analysisFramework: 379,

            categoryEditor: 380,

            weeklySnapshot: 5569,

            apiDocs: 5570,
            userExports: 621,

            notifications: 1929,

            fourHundredFour: 5571,

            browserExtension: 2000,
            stringManagement: 5572,
            clusterViz: 2999,
            visualization: 3999,
        },
        project: {
            addRegionButtonLabel: 301,
            projectSaveFailure: 1126,
            categoryEditorCreateFailure: 1127,
            frameworkCreateFailure: 1128,
            headerProjects: 173,
            addProjectButtonLabel: 301,
            discoverProjectButtonLabel: 7632,
            searchProjectPlaceholder: 302,
            addProjectModalTitle: 303,
            noProjectText: 304,
            forbiddenText: 305,
            tableHeaderName: 103,
            tableHeaderEmail: 184,
            tableHeaderRights: 160,
            tableHeaderJoinedAt: 161,
            tableHeaderActions: 16,
            deleteMemberLinkTitle: 190,
            revokeAdminRightsTitle: 188,
            grantAdminRightsTitle: 189,
            modalCancel: 61,
            modalUpdate: 323,
            modalRevert: 324,
            modalSave: 25,
            discardButtonLabel: 2007,
            modalAdd: 301,
            projectNameLabel: 103,
            projectNamePlaceholder: 39,
            projectDescriptionLabel: 200,
            projectDescriptionPlaceholder: 331,
            projectStartDateLabel: 185,
            projectStartDatePlaceholder: 333,
            projectEndDateLabel: 334,
            projectEndDatePlaceholder: 335,
            projectRegionLabel: 336,
            projectRegionPlaceholder: 337,
            projectUserGroupLabel: 338,
            projectUserGroupPlaceholder: 339,
            projectMembersLabel: 7042,
            searchRegionPlaceholder: 341,
            addRegionModalTitle: 342,
            noRegionText: 343,
            createNewRegionText: 344,
            useExistingRegionText: 345,
            tableHeaderId: 350,
            removeRegionButtonLabel: 351,
            cloneEditButtonLabel: 352,
            confirmRemoveText: 319,
            confirmCloneText: 354,
            addAfButtonLabel: 301,
            searchAfPlaceholder: 357,
            addAfModalTitle: 358,
            noAfText: 359,
            addAfTitleLabel: 13,
            addAfTitlePlaceholder: 361,
            useAfButtonLabel: 362,
            editAfButtonLabel: 363,
            cloneEditAfButtonLabel: 352,
            confirmUseAf: 365,
            confirmUseAfText: 366,
            confirmCloneAf: 354,
            addCeTitleLabel: 13,
            addCeTitlePlaceholder: 369,
            useCeButtonLabel: 362,
            editCeButtonLabel: 363,
            cloneEditCeButtonLabel: 352,
            addCeButtonLabel: 301,
            searchCePlaceholder: 370,
            addCeModalTitle: 371,
            noCeText: 372,
            confirmUseCe: 365,
            confirmUseCeText: 373,
            confirmCloneCe: 354,
            confirmCloneCeText: 374,
            generalDetailsLabel: 377,
            regionsLabel: 336,
            analysisFrameworkLabel: 379,
            categoryEditorLabel: 380,
            regionLabel: 336,
            saveButtonLabel: 25,

            // notification
            regionRemove: 205,
            regionRemoveSuccess: 206,
            regionRemoveFailure: 207,
            regionRemoveFatal: 208,
            projectDetails: 960,
            projectDetailsSuccess: 961,
            projectDetailsFailure: 962,
            projectDetailsFatal: 963,
            afCreate: 379,
            afCreateSuccess: 965,
            afCreateFailure: 966,
            afCreateFatal: 967,
            afFormEdit: 968,
            afFormEditSuccess: 969,
            afFormEditFailure: 970,
            afFormEditFatal: 971,
            countryCreate: 940,
            countryCreateSuccess: 941,
            countryCreateFailure: 942,
            countryCreateFatal: 943,
            regionSaveSuccess: 997,
            regionSave: 998,
            regionUpdate: 996,
            regionUpdateOverridden: 982,
        },
        connector: {
            noConnectorsLabel: 1115,
            headerConnectors: 1100,
            addConnectorButtonLabel: 301,
            searchConnectorPlaceholder: 1101,
            addConnectorModalTitle: 1102,
            addConnectorModalTitleLabel: 13,
            addConnectorModalTitlePlaceholder: 1103,
            addConnectorModalSourceLabel: 1104,
            addConnectorModalSourcePlaceholder: 1105,
            revokeAdminRightsTitle: 188,
            deleteMemberLinkTitle: 190,
            grantAdminRightsTitle: 189,
            noConnectorSelectedTitle: 1111,
            connectorPatchFailure: 1116,
            connectorCreateFailure: 1118,
            connectorUsersLabel: 1119,
            connectorProjectsLabel: 173,
            connectorDetailSaveLabel: 25,
            connectorDetailCancelLabel: 61,
            connectorDetailTestLabel: 1135,
            connectorTitleLabel: 13,
            noConnectorFoundLabel: 1114,
            tableHeaderTitle: 13,
            tableHeaderVisibility: 1120,
            setLocalVisibilityTitle: 1121,
            setGlobalVisibilityTitle: 1122,
            needAdminRightsTitle: 1123,
            removeProjectTitle: 1124,
            tableHeaderName: 103,
            tableHeaderEmail: 184,
            tableHeaderRights: 160,
            tableHeaderJoinedAt: 161,
            tableHeaderActions: 16,
            modalCancel: 61,
            modalCreate: 179,
            datePublishedLabel: 3,
            websiteLabel: 33,
            sourceLabel: 83,
            urlLabel: 32,
            titleLabel: 13,
            testResultsHeading: 1138,
            connectorTestFailure: 1137,

            // notification
            connectorTitle: 1113,
            connectorGetFailure: 1112,
            connectorCreateTitle: 1106,
            connectorCreateSuccess: 1107,
            connectorSourcesTitle: 1109,
            connectorPatchSuccess: 1117,
            connectorSourcesGetFailure: 1110,
            connectorUpdateOverriden: 982,
            usersTitle: 1119,
            usersListGetFailure: 999,
            projectsTitle: 31,
            projectsGetFailure: 1125,
        },
        userGroup: {
            tableHeaderName: 103,
            tableHeaderEmail: 184,
            tableHeaderStartDate: 185,
            tableHeaderCountries: 51,
            userGroupEditModalLabel: 168,
            userGroupModalDescriptionLabel: 200,
            userGroupPatchFatal: 204,
            viewMemberLinkTitle: 187,
            revokeAdminLinkTitle: 188,
            grantAdminLinkTitle: 189,
            deleteMemberLinkTitle: 190,
            addMemberErrorText: 177,
            placeholderSearch: 9,
            addMemberButtonLabel: 192,
            confirmTextRevokeAdmin: 195,
            confirmTextGrantAdmin: 196,
            confirmTextRemoveMember: 197,
            userGroupNotFound: 198,
            userGroupTitle: 201,
            userGroupActivtyLogTitle: 202,
            addProjectButtonLabel: 174,
            addUserGroupModalLabel: 13,
            addUserGroupModalPlaceholder: 178,
            tableHeaderTitle: 13,
            tableHeaderRights: 160,
            tableHeaderJoinedAt: 161,
            tableHeaderActions: 16,
            tableHeaderCreatedAt: 163,
            tableHeaderLastModifiedAt: 164,
            tableHeaderStatus: 8,
            tableHeaderMembers: 166,
            confirmTextDeleteProject: 193,
            deleteProjectLinkTitle: 172,
            headerProjects: 173,
            modalCancel: 61,
            modalSave: 25,
            viewProjectLinkTitle: 170,

            // notification
            usersPullFailure: 1928,
            userProjectDelete: 912,
            userProjectDeleteSuccess: 913,
            userProjectDeleteFailure: 914,
            userMembershipCreate: 920,
            userMembershipCreateSuccess: 921,
            userMembershipDelete: 924,
            userMembershipDeleteSuccess: 925,
            userMembershipDeleteFailure: 926,
            userMembershipDeleteFatal: 927,
            userMembershipRole: 928,
            userMembershipRoleSuccess: 929,
            userMembershipRoleFailure: 930,
            userMembershipRoleFatal: 931,
            userGroupEdit: 932,
            userGroupEditSuccess: 933,
        },
        userProfile: {
            firstNameLabel: 150,
            firstNamePlaceholder: 151,
            lastNameLabel: 152,
            lastNamePlaceholder: 153,
            organizationLabel: 154,
            organizationPlaceholder: 155,
            modalSave: 25,
            modalCancel: 61,
            modalCreate: 179,
            editProfileModalHeader: 158,
            tableHeaderTitle: 13,
            tableHeaderRights: 160,
            tableHeaderJoinedAt: 161,
            tableHeaderActions: 16,
            tableHeaderCreatedAt: 163,
            tableHeaderLastModifiedAt: 164,
            tableHeaderStatus: 8,
            tableHeaderMembers: 166,
            viewUsergroupLinkTitle: 167,
            editUsergroupLinkTitle: 168,
            deleteUsergroupLinkTitle: 169,
            viewProjectLinkTitle: 170,
            editProjectLinkTitle: 171,
            deleteProjectLinkTitle: 172,
            headerProjects: 173,
            addProjectButtonLabel: 174,
            headerGroups: 175,
            addUserGroupButtonLabel: 176,
            addUserGroupModalLabel: 13,
            addUserGroupModalPlaceholder: 178,
            confirmTextDeleteUserGroup: 194,
            confirmTextDeleteProject: 193,
            userNotFound: 199,

            // notification
            userGroupDelete: 904,
            userGroupDeleteSuccess: 905,
            userGroupDeleteFailure: 906,
            userGroupDeleteFatal: 907,
            userGroupCreate: 908,
            userGroupCreateSuccess: 909,
            userGroupCreateFailure: 910,
            userGroupCreateFatal: 911,
            userProjectDelete: 912,
            userProjectDeleteSuccess: 913,
            userProjectDeleteFailure: 914,
            userProjectDeleteFatal: 915,
            userProfileEdit: 900,
            userEditSuccess: 901,
            userEditFailure: 902,
            userEditFatal: 903,
            userEditImageUploadFailure: 7500,
            fileSelection: 5557,
            invalidFileSelection: 5556,
        },
        notifications: {
            notificationHeaderTitle: 1929,
            projectJoinResponse: 1934,
            projectJoinResponseFailure: 1935,
        },
        'notifications.projectJoin': {
            requestedToJoin: 1930,
            acceptedText: 1932,
            rejectedText: 1933,
            acceptButton: 301,
            acceptAsAdminButton: 1938,
            rejectButton: 1937,
            acceptedAsAdminText: 1939,
            date: 704,
        },
        'components.addProject': {
            addProjectModalLabel: 180,
            addProjectModalPlaceholder: 181,
            modalCancel: 61,
            modalCreate: 179,

            // notification
            userProjectCreate: 916,
            userProjectCreateSuccess: 917,
            userProjectCreateFailure: 918,
            userProjectCreateFatal: 919,
        },
        'components.addRegion': {
            cancelButtonLabel: 61,
            addRegionButtonLabel: 301,
            addRegionTitleLabel: 346,
            addRegionTitlePlaceholder: 347,
            addRegionCodeLabel: 348,
            addRegionCodePlaceholder: 349,

            // notification
            countryCreate: 940,
            countryCreateSuccess: 941,
            countryCreateFailure: 942,
            countryCreateFatal: 943,
        },
        'components.exportPreview': {
            previewNotAvailableLabel: 132,
            serverErrorText: 500,
            connectionFailureText: 501,
        },
        'components.regionAdminLevel': {
            addAdminLevelButtonLabel: 87,
            removeAdminLevelConfirm: 88,
            namePropertyLabel: 92,
            parentNamePropLabel: 96,
            parentCodePropLabel: 98,
            pcodePropertyLabel: 94,
            levelLabel: 120,
            adminLevelNameText: 121,
            actionsLabel: 16,
            adminLevelsHeader: 123,
            editAdminLevelModalTitle: 956,

            // notification
            adminLevelDelete: 948,
            adminLevelDeleteSuccess: 949,
            adminLevelDeleteFailure: 950,
            adminLevelDeleteFatal: 951,
        },
        'components.regionDetail': {
            countryCodePlaceholder: 102,
            countryNamePlaceholder: 104,
            wbRegionPlaceholer: 106,
            wbIncomeRegionPlaceholder: 108,
            ochaRegionPlaceholder: 110,
            echoRegionPlaceholder: 112,
            unGeoRegionPlaceholer: 114,
            unGeoSubregionPlaceholer: 116,
            countryCodeLabel: 101,
            countryNameLabel: 103,
            wbRegionLabel: 105,
            wbIncomeRegionLabel: 107,
            ochaRegionLabel: 109,
            echoRegionLabel: 111,
            unGeoRegionLabel: 113,
            unGeoSubregionLabel: 115,
            regionGeneralInfoLabel: 378,
        },
        'components.regionDetailView': {
            countryCodeLabel: 101,
            countryNameLabel: 103,
            wbRegionLabel: 105,
            wbIncomeRegionLabel: 107,
            ochaRegionLabel: 109,
            echoRegionLabel: 111,
            unGeoRegionLabel: 113,
            unGeoSubregionLabel: 115,
            regionGeneralInfoLabel: 378,
        },
        'components.regionMap': {
            serverErrorText: 500,
            connectionFailureText: 501,
            mapNotAvailable: 1214,
        },
        'components.simplifiedFilePreview': {
            serverErrorText: 500,
            connectionFailureText: 501,
            previewNotAvailable: 132,
        },
        'components.simplifiedLeadPreview': {
            serverErrorText: 500,
            connectionFailureText: 501,
            previewNotAvailable: 132,
            simplifyingLead: 1004,
        },
        clusterViz: {
            clusterVizTitle: 3000,
            showTable: 3001,
            keywordTableScoreLabel: 3002,
            keywordTableValueLabel: 3003,
            clusterInitRequestFatal: 3004,
            clusterDataRequestFatal: 3005,
            documentTableTitleLabel: 3006,
            documentTableClassifiedDocIdLabel: 3007,
            documentTableCreatedAtLabel: 3008,
            clusterTitle: 3009,
            clusterHeader: 3010,
            leadsCount: 3012,
            keywords: 3011,
            keywordsTitle: 3011,
            leadsTitle: 3013,
        },
        visualization: {
            visualizationTitle: 4000,
            sunburst: 4001,
            correlationMatrix: 4002,
            dendrogram: 4003,
            radialDendrogram: 4004,
            treemap: 4005,
            zoomableTreemap: 4006,
            chordDiagram: 4007,
            horizontalBar: 4008,
            forcedDirectedGraph: 4009,
            forceDirectedGraphVoronoi: 4010,
            collapsibleTree: 4011,
            orgChart: 4012,
            pieChart: 4013,
            donutChart: 4014,
            organigram: 4015,
            stackedBarChart: 4016,
            streamGraph: 4017,
            sankey: 4018,
            sparklines: 4019,
            parallelCoordinates: 4020,
        },
    },
};
export default initialDevLangState;
